/* UNION, UNION ALL : 합집합처리
- UNION : 중복데이터는 하나만 선택
- UNION ALL : 모든 데이터를 다 선택(중복데이터도)
(주의) 조회하는 컬럼의 이름, 순서, 갯수, 타입이 일치하도록 작성
************************/
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1, 2, 3);
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3, 4, 5);


--- UNION : 중복데이터는 하나만 선택
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1, 2, 3)
UNION
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3, 4, 5);

-- UNION ALL : 모든 데이터를 다 선택(중복데이터도)
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1, 2, 3)
UNION ALL
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3, 4, 5)
ORDER BY NAME; -- ORDER BY 절은 마지막에만 사용
